### PR TITLE
docs: Improve documentation for credentials use

### PR DESCRIPTION
**Pull request by grahamhar**
This is an attempt to improve the documentation as highlighted in #14

### CODE REVIEW

**Review by madpah — APPROVED** [review]

**Comment by madpah** [comment]
Hey @grahamhar - looks like some checks have failed.

Can you (locally on your branch) run `go get github.com/hashicorp/terraform-plugin-docs/cmd/tfplugindocs` and then commit the updated `go.mod` and `go.sum` please?

**Comment by grahamhar** [comment]
> Hey @grahamhar - looks like some checks have failed.
> 
> Can you (locally on your branch) run `go get github.com/hashicorp/terraform-plugin-docs/cmd/tfplugindocs` and then commit the updated `go.mod` and `go.sum` please?

Apologies @madpah I had the binary version of tfplugindocs which I used directly, changes added as you requested.

My next task will be a PR to add a new resource, but I think it would be wise to start a contributing guideline document, I'll raise an issue so that can be tracked.

**Comment by madpah** [comment]
Tests are failing seemingly due to some secrets which appear not to be accessible to this PR - I'm assuming due to it originating from outside this repository - but hard to be clear at this point.

**Comment by madpah** [comment]
"Anyone with collaborator access to this repository can use these secrets and variables for actions. They are not passed to workflows that are triggered by a pull request from a fork." - so I was correct.

**Pull request merged**
